name: 🚀 On Merge to Main, create a tag from the version in csproj

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  tag-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v3

    - name: 🔍 Extract version from csproj
      id: extract_version
      run: |
        VERSION=$(cat CodeMirror6/CodeMirror6.csproj | grep '<Version>' | sed 's/<\/\?Version>//g' | xargs)
        if [[ -z "$VERSION" ]]; then
          echo "Version not found in .csproj file"
          exit 1
        fi
        echo "Extracted version: $VERSION"
        echo "::set-output name=version::$VERSION"

    - name: 🛠️ Configure git
      if: steps.extract_version.outputs.version != ''
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: 🏷️ Create and push tag
      if: steps.extract_version.outputs.version != ''
      env:
        GITHUB_TOKEN: ${{ secrets.CI_PAT }}
      run: |
        git tag ${{ steps.extract_version.outputs.version }}
        git push https://${{ secrets.CI_PAT }}@github.com/${{ github.repository }} --tags
